<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaymentMethodSeeder extends Seeder
{
    public function run(): void
    {
        $methods = [
            // SIEUTHICODE - ACB (VND) - with bonus
            [
                'name' => 'SIEUTHICODE - ACB',
                'type' => 'bank_vn',
                'method_payment_id' => 1,
                'image' => 'https://i.imgur.com/P7EFing.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([
                    ['min' => 100000,  'percent' => 5],
                    ['min' => 500000,  'percent' => 10],
                    ['min' => 1000000, 'percent' => 15],
                ]),
                'details' => 'Sieuthicode - Ngân hàng ACB',
                'config' => json_encode([
                    'account' => '18145511',
                    'name' => 'NGUYEN VAN A',
                    'signature' => 'NAP',
                    'rate' => 26500,
                ]),
                'position' => 1,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // SIEUTHICODE - VCB (VND)
            [
                'name' => 'SIEUTHICODE - VCB',
                'type' => 'bank_vn',
                'method_payment_id' => 2,
                'image' => 'https://i.imgur.com/Fz183j7.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'Sieuthicode - Ngân hàng VCB',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 2,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // SIEUTHICODE - MBBANK (VND)
            [
                'name' => 'SIEUTHICODE - MBBANK',
                'type' => 'bank_vn',
                'method_payment_id' => 3,
                'image' => 'https://i.imgur.com/zVEduxd.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'Sieuthicode - Ngân hàng MBBANK',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 3,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // SIEUTHICODE - TCB (VND)
            [
                'name' => 'SIEUTHICODE - TCB',
                'type' => 'bank_vn',
                'method_payment_id' => 4,
                'image' => 'https://inkythuatso.com/uploads/thumbnails/800/2021/09/logo-techcombank-inkythuatso-10-15-17-50.jpg',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'Sieuthicode - Ngân hàng TCB',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 4,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // SIEUTHICODE - VTB (VND)
            [
                'name' => 'SIEUTHICODE - VTB',
                'type' => 'bank_vn',
                'method_payment_id' => 5,
                'image' => 'https://i.imgur.com/P7EFing.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'Sieuthicode - Ngân hàng VTB',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 5,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // SIEUTHICODE - BIDV (VND)
            [
                'name' => 'SIEUTHICODE - BIDV',
                'type' => 'bank_vn',
                'method_payment_id' => 6,
                'image' => 'https://i.imgur.com/znVQVCm.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'Sieuthicode - Ngân hàng BIDV',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 6,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // SIEUTHICODE - MSB (VND)
            [
                'name' => 'SIEUTHICODE - MSB',
                'type' => 'bank_vn',
                'method_payment_id' => 7,
                'image' => 'https://i.imgur.com/P7EFing.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'Sieuthicode - Ngân hàng MSB',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 7,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // SIEUTHICODE - VPB (VND)
            [
                'name' => 'SIEUTHICODE - VPB',
                'type' => 'bank_vn',
                'method_payment_id' => 8,
                'image' => 'https://i.imgur.com/P7EFing.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'Sieuthicode - Ngân hàng VPB',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 8,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // SIEUTHICODE - VAB (VND)
            [
                'name' => 'SIEUTHICODE - VAB',
                'type' => 'bank_vn',
                'method_payment_id' => 9,
                'image' => 'https://i.imgur.com/P7EFing.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'Sieuthicode - Ngân hàng VAB',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 9,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // SIEUTHICODE - SEABANK (VND)
            [
                'name' => 'SIEUTHICODE - SEABANK',
                'type' => 'bank_vn',
                'method_payment_id' => 10,
                'image' => 'https://i.imgur.com/P7EFing.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'Sieuthicode - Ngân hàng SEABANK',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 10,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // SIEUTHICODE - VIETTEL MONEY (VND)
            [
                'name' => 'SIEUTHICODE - VIETTEL MONEY',
                'type' => 'bank_vn',
                'method_payment_id' => 11,
                'image' => 'https://i.imgur.com/P7EFing.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'Sieuthicode - VIETTEL MONEY',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 11,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // SIEUTHICODE - TIMO (VND)
            [
                'name' => 'SIEUTHICODE - TIMO',
                'type' => 'bank_vn',
                'method_payment_id' => 13,
                'image' => 'https://i.imgur.com/P7EFing.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'Sieuthicode - TIMO',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 12,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // WEB2M - MOMO (VND)
            [
                'name' => 'WEB2M - MOMO',
                'type' => 'bank_vn',
                'method_payment_id' => 14,
                'image' => 'https://i.imgur.com/P7EFing.png',
                'currency' => 'VND',
                'min' => 50000,
                'max' => 50000000,
                'max_transactions' => 100,
                'max_total_funds' => 100000000,
                'bonus' => json_encode([]),
                'details' => 'WEB2M - MOMO',
                'config' => json_encode([
                    'account' => '',
                    'name' => '',
                    'signature' => '',
                    'rate' => 26500,
                ]),
                'position' => 13,
                'status' => true,
                'domain' => request()->getHost(),
            ],
            // FPayAZ - Binance - USDT (USD) - with bonus
            [
                'name' => 'FPayAZ - Binance - USDT',
                'type' => 'binance',
                'method_payment_id' => 20,
                'image' => 'https://i.imgur.com/iBEGgng.png',
                'currency' => 'USD',
                'min' => 1,
                'max' => 10000000,
                'max_transactions' => 0,
                'max_total_funds' => 0,
                'bonus' => json_encode([
                    ['min' => 10,  'percent' => 3],
                    ['min' => 50,  'percent' => 7],
                    ['min' => 100, 'percent' => 10],
                ]),
                'details' => 'FPayAZ - Binance - USDT',
                'config' => json_encode([
                    'key' => '',
                    'secret' => '',
                    'binance_id' => '228223025',
                ]),
                'position' => 14,
                'status' => true,
                'domain' => request()->getHost(),
            ],
        ];

        DB::table('payment_methods')->insert($methods);
    }
}
