@php
    $activeEvent = \App\Models\Event::where('status', true)
        ->where('start_date', '<=', now())
        ->where('end_date', '>=', now())
        ->where('domain', request()->getHost())
        ->first();
@endphp

@if($activeEvent && auth()->check() && $activeEvent->canUserSpin(auth()->id()))
@php
    $remainingToday = $activeEvent->getRemainingSpinsToday(auth()->id());
    $rewards = $activeEvent->rewards ?? [];
    $user = auth()->user();
    $userCurrency = $user->currency ?? 'VND';
    
    // Lấy dữ liệu currency từ Currency table
    $currencyData = \App\Models\Currency::where('code', $userCurrency)->first();
    $exchangeRate = $currencyData ? $currencyData->exchange_rate : 1;
    $currencySymbol = $currencyData && $currencyData->symbol ? $currencyData->symbol : '$';
    $symbolPosition = $currencyData && $currencyData->symbol_position ? $currencyData->symbol_position : 'before'; // before hoặc after
@endphp

<!-- ================= FLOATING GIFTBOX ================= -->
<div id="event-giftbox"
     class="position-fixed"
     style="bottom:20px;right:20px;z-index:1050;cursor:pointer;">
    <img src="/template-admin/images/giftbox.png"
         class="event-giftbox-img"
         alt="Event Gift">
</div>

<!-- ================= MODAL ================= -->
<div class="modal fade" id="eventModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered event-modal-dialog">
        <div class="modal-content border-0 shadow-lg rounded-3 overflow-hidden">

            <div class="modal-header bg-primary text-white py-2 px-3">
                <h6 class="modal-title mb-0">🎁 {{ $activeEvent->name }}</h6>
                <button type="button"
                        class="btn btn-link text-white p-0"
                        data-bs-dismiss="modal"
                        style="font-size:20px;opacity:0.8;transition:all 0.2s ease;"
                        aria-label="Close">
                    <i class="bx bx-x"></i>
                </button>
            </div>

            <div class="modal-body p-3 event-modal-body">

                <!-- GIFT BOXES GRID -->
                <div id="gift-boxes-container" class="mb-3" style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;perspective:1000px;">
                    <!-- Boxes will be generated by JS -->
                </div>

                <!-- INFO -->
                <div class="text-center mb-2">
                    <p class="mb-1" style="font-size:13px;">
                        Còn <span class="badge bg-warning text-dark">{{ $remainingToday }}</span> lượt
                    </p>
                    <small class="text-muted" style="font-size:11px;">Chọn hộp quà để mở</small>
                </div>

                <!-- RESULT -->
                <div id="result-area" style="display:none">
                    <div class="alert alert-success text-center py-3 px-3 mb-2" style="border:none;background:linear-gradient(135deg,rgba(40,167,69,0.1),rgba(32,201,151,0.1));">
                        <p id="result-message" class="mb-0" style="font-size:14px;line-height:1.6;"></p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- ================= STYLE ================= -->
<style>
.event-giftbox-img{
    width:70px;
    animation:bounce 2s infinite;
    filter: drop-shadow(0 2px 8px rgba(0,0,0,0.15));
}
@keyframes bounce{
    0%,100%{transform:translateY(0)}
    50%{transform:translateY(-10px)}
}

.modal-header .btn-link {
    text-decoration: none;
}

.modal-header .btn-link:hover {
    opacity: 1 !important;
    transform: scale(1.2) rotate(90deg);
}

.modal-header .btn-link:active {
    transform: scale(0.95) rotate(90deg);
}

/* Modal Dialog */
.event-modal-dialog {
    width: 95%;
    max-width: 420px;
    margin: auto;
}

.event-modal-body {
    max-height: 70vh;
    overflow-y: auto;
    overflow-x: hidden;
    background: #f8f9fa;
}

.gift-box-item{
    width:100%;
    aspect-ratio:1;
    position:relative;
    transform-style:preserve-3d;
    transition:transform .3s ease;
    cursor:pointer;
    border-radius:12px;
}

.gift-box-item:hover:not(.disabled){
    transform:scale(1.08) rotateY(8deg) rotateX(-5deg);
    filter: drop-shadow(0 8px 16px rgba(102, 126, 234, 0.3));
}

.gift-box-item:active:not(.disabled){
    transform:scale(0.95);
}

.gift-box-front, .gift-box-back{
    position:absolute;
    width:100%;
    height:100%;
    backface-visibility:hidden;
    -webkit-backface-visibility:hidden;
    border-radius:12px;
    display:flex;
    align-items:center;
    justify-content:center;
}

.gift-box-front{
    background:linear-gradient(135deg, #ffffff 0%, #f5f5f5 100%);
    border:2px solid #e0e0e0;
    box-shadow:0 4px 12px rgba(0,0,0,0.08), inset 0 1px 0 rgba(255,255,255,0.8);
}

.gift-box-front img{
    width:75%;
    height:75%;
    object-fit:contain;
    filter: drop-shadow(0 2px 4px rgba(0,0,0,0.1));
}

.gift-box-back{
    transform:rotateY(180deg);
    border-radius:12px;
    display:flex;
    align-items:center;
    justify-content:center;
    color:white;
    font-weight:bold;
    font-size:11px;
    text-align:center;
    padding:6px;
    box-shadow:0 4px 12px rgba(0,0,0,0.15);
}

.gift-box-item.shake{
    animation:shake .4s cubic-bezier(0.36, 0, 0.66, -0.56);
}

@keyframes shake{
    0%,100%{transform:rotate(0) scale(1)}
    10%{transform:rotate(-8deg) scale(1.02)}
    20%{transform:rotate(8deg) scale(1.02)}
    30%{transform:rotate(-6deg) scale(1.01)}
    40%{transform:rotate(6deg) scale(1.01)}
    50%{transform:rotate(-4deg)}
    60%{transform:rotate(4deg)}
    70%{transform:rotate(-2deg)}
    80%{transform:rotate(2deg)}
    90%{transform:rotate(-1deg)}
}

.gift-box-item.flip{
    animation:flipBox .7s cubic-bezier(0.68, -0.55, 0.265, 1.55) forwards;
}

@keyframes flipBox{
    0%{transform:rotateY(0) scale(1)}
    50%{transform:rotateY(90deg) scale(1.05)}
    100%{transform:rotateY(180deg) scale(1)}
}

.gift-box-item.explode{
    animation:explode .5s cubic-bezier(0.36, 0, 0.66, -0.56) forwards;
}

@keyframes explode{
    0%{
        transform:scale(1);
        opacity:1;
        filter:brightness(1);
    }
    30%{
        transform:scale(1.15);
        opacity:0.9;
        filter:brightness(1.2);
    }
    100%{
        transform:scale(0);
        opacity:0;
        filter:brightness(0.5);
    }
}

.gift-box-item.disabled{
    pointer-events:none;
    opacity:0.5;
    filter:grayscale(50%);
}

/* Desktop - 1200px+ */
@media(min-width:1200px){
    .event-modal-dialog {
        max-width: 450px;
    }
    
    #gift-boxes-container{
        gap:12px !important;
    }
}

/* Tablet - 768px to 1199px */
@media(min-width:768px) and (max-width:1199px){
    .event-modal-dialog {
        max-width: 400px;
    }
    
    #gift-boxes-container{
        gap:10px !important;
    }
    
    .gift-box-back{
        font-size:10px;
    }
    
    .event-modal-body {
        max-height: 65vh;
        padding: 12px !important;
    }
}

/* Small Tablet - 576px to 767px */
@media(min-width:576px) and (max-width:767px){
    .event-modal-dialog {
        width: 90%;
        max-width: 380px;
    }
    
    #gift-boxes-container{
        grid-template-columns:repeat(2,1fr) !important;
        gap:8px !important;
    }
    
    .gift-box-back{
        font-size:9px;
    }
    
    .event-modal-body {
        max-height: 60vh;
        padding: 10px !important;
    }
}

/* Mobile - 360px to 575px */
@media(max-width:575px){
    .event-modal-dialog {
        width: 92%;
        max-width: 360px;
    }
    
    #gift-boxes-container{
        grid-template-columns:repeat(2,1fr) !important;
        gap:8px !important;
    }
    
    .event-giftbox-img{
        width:60px;
    }
    
    .gift-box-back div{
        font-size:9px;
    }
    
    .event-modal-body {
        max-height: 55vh;
        padding: 10px !important;
    }
}

/* Small Mobile - Below 360px */
@media(max-width:359px){
    .event-modal-dialog {
        width: 95%;
        max-width: 320px;
    }
    
    #gift-boxes-container{
        grid-template-columns:repeat(2,1fr) !important;
        gap:6px !important;
    }
    
    .gift-box-front img{
        width:70%;
        height:70%;
    }
    
    .event-modal-body {
        max-height: 50vh;
        padding: 8px !important;
    }
}
</style>

<!-- ================= SCRIPT ================= -->
<script>
const eventData = @json($activeEvent);
const rewards   = @json($rewards);
const exchangeRate = {{ $exchangeRate }};
const currencySymbol = '{{ $currencySymbol }}';
const symbolPosition = '{{ $symbolPosition }}';
let isProcessing = false;
let selectedRewardIndex = null;
let giftBoxes = [];

// Hàm tính amount theo currency (amount * exchange_rate)
function convertAmount(amount) {
    return Math.round((amount * exchangeRate) * 100) / 100;
}

// Hàm format tiền tệ theo symbol_position
function formatCurrency(amount) {
    const converted = convertAmount(amount).toLocaleString('en-US', {minimumFractionDigits: 0, maximumFractionDigits: 2});
    
    if (symbolPosition === 'after') {
        return `${converted}${currencySymbol}`;
    } else {
        return `${currencySymbol}${converted}`;
    }
}

// Hàm format tiền tệ từ API response
function formatCurrencyFromResponse(amount, currency) {
    const formatted = parseFloat(amount).toLocaleString('en-US', {minimumFractionDigits: 0, maximumFractionDigits: 2});
    
    if (currency.symbol_position === 'after') {
        return `${formatted}${currency.symbol}`;
    } else {
        return `${currency.symbol}${formatted}`;
    }
}

// Hàm chọn phần thưởng theo xác suất
function selectRewardByProbability() {
    const totalProbability = rewards.reduce((sum, r) => sum + (r.probability || 0), 0);
    let random = Math.random() * totalProbability;
    
    for (let i = 0; i < rewards.length; i++) {
        random -= (rewards[i].probability || 0);
        if (random <= 0) return i;
    }
    return 0;
}

// Tạo hộp quà
function initGiftBoxes() {
    const container = document.getElementById('gift-boxes-container');
    container.innerHTML = '';
    giftBoxes = [];
    
    // Tạo 9 hộp quà
    for (let i = 0; i < 9; i++) {
        const box = document.createElement('div');
        box.className = 'gift-box-item';
        box.innerHTML = `
            <div class="gift-box-front">
                <img src="/template-admin/images/giftbox.png" alt="Gift">
            </div>
            <div class="gift-box-back" style="background:linear-gradient(135deg,#667eea,#764ba2);">
                <div>
                    <div style="font-size:24px;margin-bottom:4px;">🎁</div>
                    <div>Phần thưởng</div>
                </div>
            </div>
        `;
        
        box.addEventListener('click', () => openGiftBox(i));
        container.appendChild(box);
        giftBoxes.push(box);
    }
}

// Mở hộp quà
function openGiftBox(boxIndex) {
    if (isProcessing) return;
    isProcessing = true;
    
    try {
        // Chọn phần thưởng theo xác suất
        selectedRewardIndex = selectRewardByProbability();
        const reward = rewards[selectedRewardIndex];
        
        // Shake animation cho hộp được chọn
        giftBoxes[boxIndex].classList.add('shake');
        giftBoxes.forEach((box, idx) => {
            if (idx !== boxIndex) box.classList.add('disabled');
        });
        
        setTimeout(() => {
            giftBoxes[boxIndex].classList.remove('shake');
            
            // Cập nhật nội dung phía sau
            const backDiv = giftBoxes[boxIndex].querySelector('.gift-box-back');
            backDiv.style.background = reward.color || 'linear-gradient(135deg,#667eea,#764ba2)';
            backDiv.innerHTML = `
                <div>
                    <div style="font-size:24px;margin-bottom:4px;">🎉</div>
                    <div>${reward.name}</div>
                </div>
            `;
            
            // Flip animation
            giftBoxes[boxIndex].classList.add('flip');
            
            setTimeout(() => {
                // Hiệu ứng nổ hộp quà
                giftBoxes[boxIndex].classList.add('explode');
                
                setTimeout(() => {
                    // Hiển thị kết quả
                    document.getElementById('gift-boxes-container').style.display = 'none';
                    document.getElementById('result-area').style.display = 'block';
                    
                    // Gọi API
                    fetch(`/events/${eventData.id}/spin`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
                        }
                    })
                    .then(r => r.json())
                    .then(data => {
                        if (data.success) {
                            // Hiển thị displayAmount từ API
                            const displayAmount = formatCurrencyFromResponse(data.displayAmount, data.currency);
                            const resultMsg = `Chúc mừng bạn đã nhận được<br><span style="font-size:20px;color:#28a745;font-weight:bold;">${displayAmount}</span>`;
                            document.getElementById('result-message').innerHTML = resultMsg;
                        } else {
                            // Hiển thị lỗi chi tiết
                            const errorMsg = data.message || 'Có lỗi xảy ra. Vui lòng thử lại.';
                            const resultMsg = `<span style="color:#dc3545;font-weight:bold;">${errorMsg}</span>`;
                            document.getElementById('result-message').innerHTML = resultMsg;
                            console.error('[API ERROR]', data);
                        }
                    })
                    .catch(err => {
                        console.error('[FETCH ERROR]', err);
                        const resultMsg = `<span style="color:#dc3545;font-weight:bold;">Có lỗi kết nối. Vui lòng thử lại.</span>`;
                        document.getElementById('result-message').innerHTML = resultMsg;
                    });
                    
                    isProcessing = false;
                }, 300);
            }, 800);
        }, 500);
    } catch (err) {
        console.error('[OPEN GIFT ERROR]', err);
        isProcessing = false;
    }
}

/* OPEN MODAL */
document.addEventListener('DOMContentLoaded', () => {
    const giftbox = document.getElementById('event-giftbox');
    const modalEl = document.getElementById('eventModal');

    if (!giftbox || !modalEl) {
        console.error('[EVENT] Missing element');
        return;
    }

    giftbox.addEventListener('click', () => {
        try {
            if ({{ $remainingToday }} <= 0) {
                console.warn('[EVENT] No spins left');
                alert('Bạn đã hết lượt quay hôm nay');
                return;
            }

            // Khởi tạo hộp quà
            initGiftBoxes();

            // Compatible with Bootstrap 4 & 5
            if (typeof bootstrap !== 'undefined' && bootstrap.Modal) {
                if (bootstrap.Modal.getOrCreateInstance) {
                    bootstrap.Modal.getOrCreateInstance(modalEl).show();
                } else {
                    new bootstrap.Modal(modalEl).show();
                }
            } else if (typeof $ !== 'undefined') {
                $(modalEl).modal('show');
            } else {
                throw new Error('Bootstrap not loaded');
            }
        } catch (e) {
            console.error('[EVENT MODAL ERROR]', e);
        }
    });
});

/* RESET */
document.getElementById('eventModal')?.addEventListener('hidden.bs.modal', () => {
    document.getElementById('gift-boxes-container').style.display = 'grid';
    document.getElementById('result-area').style.display = 'none';
    giftBoxes.forEach(box => {
        box.className = 'gift-box-item';
    });
    isProcessing = false;
});
</script>
@endif
